apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: cron-scaledobject
spec:
  minReplicaCount: 4
  scaleTargetRef:
    name: workertests-cron
  triggers:
  - type: cron
    metadata:
      timezone: America/Sao_Paulo
      start: 48 15 * * *
      end: 51 15 * * *
      desiredReplicas: "8"