apiVersion: apps/v1
kind: Deployment
metadata:
  name:  worker-devops-experience
  labels:
    app:  worker-devops-experience
spec:
  selector:
    matchLabels:
      app: worker-devops-experience
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  worker-devops-experience
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  worker-devops-experience
        image: renatogroffe/workertests-dotnet8:2
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
      restartPolicy: Always